In [4]:
# NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. 
# It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python 
# and PyData ecosystems. 
# NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and 
# industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, 
# scikit-learn, scikit-image and most other data science and scientific Python packages.

In [5]:
# used in ML, NLP

In [6]:
# numpy something based on tenserflow, pytorch

In [8]:
# numPy was original package inside python so it was actually a package in Matlab (Tool), later introduce in python named as
# numPy (Numerical Python)

In [2]:
import numpy as np

In [11]:
# Not best as numPy
import array

In [12]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [15]:
type(np.array([1,2,3,4,5,6]))

# nd --> n-dimensional array

numpy.ndarray

### upCasting in numPy:

In [ ]:
# upcasting in numpy: 

# A NumPy array has the dtype attribute, which specifies the data type of all the elements in the array.
# If the array contains elements of different data types, all the elements are cast into the largest 
# type (a process known as upcasting). A NumPy array can also be a copy or a reference to an existing NumPy array.

In [19]:
# 1d-array
np.array([1,2,3,4, "Hello World", 4+8j])

array(['1', '2', '3', '4', 'Hello World', '(4+8j)'], dtype='<U64')

In [20]:
np.array([1,2,3,4,5, 6.8])

array([1. , 2. , 3. , 4. , 5. , 6.8])

In [21]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [23]:
# 2d-array
np.array([[1,3],[3,4], [1,2,3]])

# the no. of element in array is not same so its give warning but it holds the data in the form of list then put these
# list into an nd-array

C:\Users\adv\AppData\Local\Temp\ipykernel_7792\1959913074.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4], [1,2,3]])


array([list([1, 3]), list([3, 4]), list([1, 2, 3])], dtype=object)

In [27]:
# 3d-array
np.array([ [ [1,2,3], [4,5,6] ], [[4,5,6], [9,8,7]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [9, 8, 7]]])

In [28]:
# ndmin add dimension which we pass to it
np.array([1,2,3] , ndmin = 3)

array([[[1, 2, 3]]])

In [29]:
np.array([1,2,3] , ndmin = 10)

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [30]:
# dtype --> take data type and done type casting

np.array([1,2,3] , dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [103]:
arr = np.array([(1,2) , (4,5)],dtype = [("a",'<i4'), ("b",'<i8')])

In [104]:
arr

# by default is i4
# i4 represent 32bit and i8 represent 64bits
# i2 also exist

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [105]:
type(arr[0][0])

numpy.int32

In [106]:
type(arr[0][1])

numpy.int64

In [107]:
arr  = np.array([[1,3],[3,4]])

In [108]:
type(arr[0][0])

numpy.int32

In [109]:
type(arr[0][1])

numpy.int32

#### Another DataType --> Matrix

In [110]:
np.mat(arr)
# MATRIX

# np.matrix(arr)

matrix([[1, 3],
        [3, 4]])

In [111]:
mat = np.matrix(arr)

In [112]:
# Convert list into array with different method

In [113]:
l = [1,2,3,4,5]

In [114]:
np.array(l)

array([1, 2, 3, 4, 5])

In [115]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [116]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [117]:
# Matrix is a subset of array

In [118]:
# asanyarray() -- convert array into matrix

np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [119]:
np.asarray(mat)

# convert matrix into array

array([[1, 3],
       [3, 4]])

In [120]:
# if I want to check that matrix are the sub class of nd-array or not
issubclass(np.matrix, np.ndarray)

True

In [121]:
# array are the parent class of matrix so it will be FALSE
issubclass(np.ndarray, np.matrix)

False

In [122]:
# assign arr to variable
# array are mutable

In [123]:
a = arr

# this is something called "Shollow Copy" so it'll effect means if we changing in one then it will automatically 
# effect the others

In [124]:
b = np.copy(arr)

# this is representing a "deep copy" so it will copy the value and does not effect the others

In [125]:
# changing the value of arr
arr[0][0] = 67

In [126]:
arr

array([[67,  3],
       [ 3,  4]])

In [127]:
# b will hold old data
b

array([[1, 3],
       [3, 4]])

In [130]:
# access value of array

In [131]:
arr[-1]

array([3, 4])

In [132]:
arr[-1][-1]

4

In [133]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [134]:
for i in arr:
    for j in i:
        print(j)

67
3
3
4


In [135]:
# fromFunction()

In [136]:
type(np.fromfunction(lambda i , j :i==j,(4,4)))

numpy.ndarray

In [137]:
np.fromfunction(lambda i , j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [3]:
np.fromfunction(lambda i, j: i**j, (3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [4]:
np.fromfunction(lambda i,j: i+j, (3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [6]:
np.fromfunction(lambda i , j :i/j,(3,3))

# numPy doesnot give any kind of error in dividing 0/0 but its show that this is "nan" and similar to (1/0) --> inf(infinity)

C:\Users\adv\AppData\Local\Temp\ipykernel_9696\1015003607.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))
C:\Users\adv\AppData\Local\Temp\ipykernel_9696\1015003607.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [8]:
0/0
# error --> ZeroDivisionError

ZeroDivisionError: division by zero

In [9]:
1/0

ZeroDivisionError: division by zero

In [10]:
# fromiter --> even from a iterable variable or a iter you will be able to generate a data

In [11]:
# list comprehension

[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [28]:
# generator
gen = (i*i for i in range(5))

In [29]:
# yield --> with the help of yield function I will be able create any function as an generator function

In [30]:
def test(x):
    yield x

In [31]:
test(5)

<generator object test at 0x00000285888A52E0>

In [32]:
gen
for i in gen :
    print(i)

0
1
4
9
16


In [21]:
np.fromiter(range(5),dtype= int) 
# range is also a generator()

array([0, 1, 2, 3, 4])

In [24]:
np.fromiter(gen,dtype= int)

array([ 0,  1,  4,  9, 16])

In [33]:
np.fromstring('1,3,4,5,5' , sep = ',', dtype= int)

array([1, 3, 4, 5, 5])

In [34]:
np.fromstring("456 456 3454 34543" ,sep = ' ', dtype= complex)

array([  456.+0.j,   456.+0.j,  3454.+0.j, 34543.+0.j])